Repository GSG-CF05/Team5-Novelty-Travels, pull requests merged in 2022-03, with the labels that each got.

#3 add file structure
  assets/icons/icon.png
  assets/images/landing-page/logo.png
  assets/images/landing-page/travel.png
  destination-page/destination.html
  destination-page/js/destination.js
  destination-page/styles/destination.css
  destination-page/styles/media.css
  holidays-page/holidays.html
  holidays-page/js/holidays.js
  holidays-page/styles/holidays.css
  holidays-page/styles/media.css
  home-page/home.html
  home-page/js/home.js
  home-page/styles/home.css
  home-page/styles/media.css
  index.html
  js/landing.js
  locations-page/js/locations.js
  locations-page/locations.html
  locations-page/styles/locations.css
  locations-page/styles/media.css
  styles/global.css
  styles/landing.css
  styles/media.css
Labels: awaiting-review

#10 create readme file, actual time 4h
  README.md
Labels: T4h, awaiting-review

#11 4 landing page mobile
  README.md
  index.html
  styles/global.css
  styles/landing.css
Labels: T1h, awaiting-review
